
stages:
  data_ingestion:
    cmd: python src/IBM_anti_launder_transaction/pipeline/stage_01_data_ingestion.py
    deps:
      - src/IBM_anti_launder_transaction/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/sample.zip


  data_validation:
    cmd: python src/IBM_anti_launder_transaction/pipeline/stage_02_data_validation.py
    deps:
      - src/IBM_anti_launder_transaction/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python src/IBM_anti_launder_transaction/pipeline/stage_03_data_transformation.py
    deps:
      - src/IBM_anti_launder_transaction/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/sample.zip

    outs:
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

  model_trainer:
    cmd: python src/IBM_anti_launder_transaction/pipeline/stage_04_model_trainer.py
    deps:
      - src/IBM_anti_launder_transaction/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/sample.zip
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv

    outs:
      - artifacts/model_trainer/model.joblib


  model_evaluation:
    cmd: python src/IBM_anti_launder_transaction/pipeline/stage_05_model_evaluation.py
    deps:
      - src/IBM_anti_launder_transaction/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/sample.zip
      - artifacts/data_transformation/preprocessor.joblib
      - artifacts/model_trainer/model.joblib
    
    outs:
      - artifacts/model_evaluation/metrics.json